-- Generated by HyprMod

-- Settings
hl.config({
    animations = {
        enabled = true,
    },
    decoration = {
        blur = {
            ignore_opacity = true,
            xray = false,
        },
        dim_special = 0.7,
    },
    general = {
        border_size = 0,
        gaps_in = 5,
    },
    gestures = {
        workspace_swipe_direction_lock = false,
        workspace_swipe_distance = 100,
        workspace_swipe_forever = true,
    },
    input = {
        numlock_by_default = true,
        touchpad = {
            scroll_factor = 1.2,
        },
    },
    misc = {
        animate_mouse_windowdragging = true,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
})

-- Bezier curves
hl.curve("easeInSine", { type = "bezier", points = { {0.12, 0.0}, {0.39, 0.0} } })

-- Animations
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "windowsOut",
    enabled = false,
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 1.0,
    bezier = "easeInSine",
})
