##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}
windowrule {
    name = lxqt-policykit-float
    match:class = lxqt-policykit-agent
    float = yes
    center = yes
}
general {
    col.active_border = rgba(83A598FF)
    col.inactive_border = rgba(32302FFF)
}
animations {
    enabled = true

    # animation = NAME, ONOFF, SPEED, CURVE [, STYLE]
    # SPEED is in deciseconds (1 = 100ms) — smaller = faster
    animation = windows, 1, 2, default, popin 80%
    animation = windowsOut, 1, 2, default, popin 80%
    animation = fade, 1, 2, default
    animation = workspaces, 1, 3, default
}
windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
